extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
parser: babel-eslint
env:
  browser: true
  node: true
rules:
  linebreak-style: 0
  no-unused-vars: 1
  no-console: 0
  no-use-before-define: 0
  no-param-reassign: 0
  arrow-parens: 0
  function-paren-newline: 0
  object-curly-newline: 0
  quotes: 0
  quote-props: 0
  comma-dangle: 0
  react/jsx-filename-extension: 
    - 1
    - extensions: 
      - .js
      - .jsx
  react/prefer-stateless-function: 0
  react/no-did-mount-set-state: 0
